version: '3'
services:
  app:
    image: keune/go-kv
    container_name: gokv_app
    restart: always
    tty: true
    depends_on:
      - redis
    build:
      context: .
      dockerfile: ./app/Dockerfile
    environment:
      SERVICE_NAME: gokv
      TZ: ${GNR_TIMEZONE}
    volumes:
      - "./app:/go/src/app"
    networks:
      - gokv-network
    ports:
      - "${APP_PORT}:80"
  redis:
      image: redis:5.0.7-alpine
      container_name: gokv_redis
      restart: always
      environment:
        TZ: ${GNR_TIMEZONE}
      networks:
      - gokv-network

networks:
  gokv-network:
    driver: bridge
